src/Entity/Dish.php
<?php

namespace App\Entity;

use App\Repository\DishRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DishRepository::class)]
class Dish
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $dish_name;

    #[ORM\Column(type: 'string', length: 255)]
    private $description;

    #[ORM\Column(type: 'float')]
    private $price;

    #[ORM\Column(type: 'string', length: 255)]
    private $type;

    #[ORM\Column(type: 'string', length: 255)]
    private $photo;

    #[ORM\OneToMany(mappedBy: 'id_dish', targetEntity: Favorite::class)]
    private $favorites;

    #[ORM\ManyToMany(targetEntity: Cart::class, mappedBy: 'id_dish')]
    private $carts;

    public function __construct()
    {
        $this->favorites = new ArrayCollection();
        $this->carts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDishName(): ?string
    {
        return $this->dish_name;
    }

    public function setDishName(string $dish_name): self
    {
        $this->dish_name = $dish_name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * @return Collection|Favorite[]
     */
    public function getFavorites(): Collection
    {
        return $this->favorites;
    }

    public function addFavorite(Favorite $favorite): self
    {
        if (!$this->favorites->contains($favorite)) {
            $this->favorites[] = $favorite;
            $favorite->setIdDish($this);
        }

        return $this;
    }

    public function removeFavorite(Favorite $favorite): self
    {
        if ($this->favorites->removeElement($favorite)) {
            // set the owning side to null (unless already changed)
            if ($favorite->getIdDish() === $this) {
                $favorite->setIdDish(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Cart[]
     */
    public function getCarts(): Collection
    {
        return $this->carts;
    }

    public function addCart(Cart $cart): self
    {
        if (!$this->carts->contains($cart)) {
            $this->carts[] = $cart;
            $cart->addIdDish($this);
        }

        return $this;
    }

    public function removeCart(Cart $cart): self
    {
        if ($this->carts->removeElement($cart)) {
            $cart->removeIdDish($this);
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Boolean;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

/**
 * @UniqueEntity(fields={"id_user"}, message="There is already an account with this id_user")
 */
#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue (strategy:"AUTO")]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255, unique : true)]
    private $id_user;

    #[ORM\Column(type: 'string', length: 255, unique : true)]
    private $pwd_user;

    #[ORM\Column(type: 'string', length: 255, unique : true)]
    private $mail;

    #[ORM\Column(type: 'string', length: 255)]
    private $first_name;

    #[ORM\Column(type: 'string', length: 255)]
    private $last_name;

    #[ORM\Column(type: 'string', length: 255)]
    private $adress;

    #[ORM\Column(type: 'string', length: 255)]
    private $gender;

    #[ORM\OneToMany(mappedBy: 'id_user', targetEntity: Message::class)]
    private $user_message;

    #[ORM\OneToMany(mappedBy: 'id_user', targetEntity: Favorite::class)]
    private $user_fav;

    #[ORM\OneToMany(mappedBy: 'id_user', targetEntity: Cart::class)]
    private $user_cart;

    #[ORM\OneToMany(mappedBy: 'id_user', targetEntity: Reservation::class)]
    private $user_reservation;

    #[ORM\Column(type: 'json')]
    private array $level = [];

    #[ORM\Column(type: 'datetime_immutable')]
    private $createdAt;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private $deletedAt;

    public function __construct()
    {
        $this->user_message = new ArrayCollection();
        $this->user_fav = new ArrayCollection();
        $this->user_cart = new ArrayCollection();
        $this->user_reservation = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdUser(): ?string
    {
        return $this->id_user;
    }

    public function setIdUser(string $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getPwdUser(): ?string
    {
        return $this->pwd_user;
    }

    public function setPwdUser(string $pwd_user): self
    {
        $this->pwd_user = $pwd_user;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getUserMessage(): Collection
    {
        return $this->user_message;
    }

    public function addUserMessage(Message $userMessage): self
    {
        if (!$this->user_message->contains($userMessage)) {
            $this->user_message[] = $userMessage;
            $userMessage->setIdUser($this);
        }

        return $this;
    }

    public function removeUserMessage(Message $userMessage): self
    {
        if ($this->user_message->removeElement($userMessage)) {
            // set the owning side to null (unless already changed)
            if ($userMessage->getIdUser() === $this) {
                $userMessage->setIdUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Favorite[]
     */
    public function getUserFav(): Collection
    {
        return $this->user_fav;
    }

    public function addUserFav(Favorite $userFav): self
    {
        if (!$this->user_fav->contains($userFav)) {
            $this->user_fav[] = $userFav;
            $userFav->setIdUser($this);
        }

        return $this;
    }

    public function removeUserFav(Favorite $userFav): self
    {
        if ($this->user_fav->removeElement($userFav)) {
            // set the owning side to null (unless already changed)
            if ($userFav->getIdUser() === $this) {
                $userFav->setIdUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Cart[]
     */
    public function getUserCart(): Collection
    {
        return $this->user_cart;
    }

    public function addUserCart(Cart $userCart): self
    {
        if (!$this->user_cart->contains($userCart)) {
            $this->user_cart[] = $userCart;
            $userCart->setIdUser($this);
        }

        return $this;
    }

    public function removeUserCart(Cart $userCart): self
    {
        if ($this->user_cart->removeElement($userCart)) {
            // set the owning side to null (unless already changed)
            if ($userCart->getIdUser() === $this) {
                $userCart->setIdUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getUserReservation(): Collection
    {
        return $this->user_reservation;
    }

    public function addUserReservation(Reservation $userReservation): self
    {
        if (!$this->user_reservation->contains($userReservation)) {
            $this->user_reservation[] = $userReservation;
            $userReservation->setIdUser($this);
        }

        return $this;
    }

    public function removeUserReservation(Reservation $userReservation): self
    {
        if ($this->user_reservation->removeElement($userReservation)) {
            // set the owning side to null (unless already changed)
            if ($userReservation->getIdUser() === $this) {
                $userReservation->setIdUser(null);
            }
        }

        return $this;
    }

    public function getRoles(): array
    {
        return $this->getLevel();
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function getUserIdentifier(): string
    {
        return $this->id_user;
    }

    public function getPassword(): ?string
    {
        return $this->pwd_user;
    }

    public function getLevel(): array
    {
        return $this->level;
    }

    public function setLevel(array $level): self
    {
        $this->level = $level;
        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeImmutable
    {
        return $this->deletedAt;
    }

    public function setDeletedAt(?\DateTimeImmutable $deletedAt): self
    {
        $this->deletedAt = $deletedAt;

        return $this;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\RegistrationFormType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\UserAuthenticatorInterface;

class UserController extends AbstractController
{
	
	#[Route('/{_locale<%app.supported_locales%>}/myAccount', name: 'account')]
	
	public function myAccount(): Response
	{
		return $this->render("user/account.html.twig");
	
	}
	
    #[Route('/updateInfo', name: 'updateInfo')]
    public function register(Request $request, UserPasswordHasherInterface $userPasswordHasher, EntityManagerInterface $entityManager, UserRepository $userRepository): Response
    {
	    $user = $this->getUser();
        $form = $this->createForm(RegistrationFormType::class, $user);

        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $user->setPwduser(
                $userPasswordHasher->hashPassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );
            $entityManager->persist($user);
            $entityManager->flush();
			return $this->myAccount();
        }

        return $this->render('user/updateInfoClient.html.twig', [
            'updateInfoForm' => $form->createView(),
        ]);
    }

}

templates/user/account.html.twig
{% extends 'base.html.twig' %}

{% block title %}My Account{% endblock %}

{% block body %}

<div class="shadow-lg p-3 mb-5 bg-white rounded">
    <div class="card text-center">
        <div class="card-header">
            {{ "My Account" |trans}}
        </div>
        <div class="card-body">
            <h5 class="card-title"> {{ "Welcome to your account" |trans}}  {{ app.user.idUser }} !</h5>
            <p class="card-text"> {{ "Feel free to check and update your information below." |trans}} </p>
            <table class="table">
                <tbody>
                    <tr>
                        <td>
                            <h6 class="textDesc">{{ "Username : " |trans}}{{ app.user.idUser }}</h6>

                        </td>
                    </tr>
                    <tr>
                        <td>
                            <h6 class="textDesc">{{ "Email :" |trans}} {{ app.user.mail }}</h6>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <h6 class="textDesc">{{ "First Name :" |trans}} {{ app.user.firstName }}</h6>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <h6 class="textDesc">{{ "Last Name :" |trans}} {{ app.user.lastName }}</h6>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <h6 class="textDesc">{{ "Gender :" |trans}} {{ app.user.gender }}</h6>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <h6 class="textDesc">{{ "Adress :" |trans}} {{ app.user.adress }}</h6>
                        </td>
                    </tr>
                </tbody>
            </table>
            <a class="btn btn-primary btn-lg btn-block" href="{{ path('updateInfo') }}?id={{ app.user.id }}">{{ "Update" |trans}}</a>
        <div class="card-footer text-muted">
            GustoHelpService
        </div>
    </div>
    </div>
</div>
{% endblock %}

templates/user/cart.html.twig
{% extends 'base.html.twig' %}
{% block header %} <link rel="stylesheet" href="{{ asset('css/menuStyle.css') }}" />{% endblock %}

{% block title %}Cart{% endblock %}

{% block body %}
    <div class="shadow-lg p-5 mb-5 bg-white rounded container">
        <div class="card text-center">
            <div class="card-header">
                {{ "Your cart" |trans}}
            </div>
            <div class="card-body">
                <h5 class="card-title"> {{ "Coming back for your best picks ?" |trans}}</h5>
                <p class="card-text"> {{ "Gusto will never fail you !" |trans}} MAMMA MIA !</p>
                <table class="table">
                    {% set total = 0 %}
                    {% for c in cart %}
                        {% if c.status == "open" %}
                            {% for key, value in c.idDish %}
                                {% for dish in dishes %}
                                    {% if dish.id == key %}
                                        {% if dish.archived != 1 %}
                                            {% set total = total+(dish.price*value) %}
                                            <tr>
                                                <td>
                                                    <img class="imgMenu" src="{{ asset(dish.photo) }}" alt="{{ dish.dishName }}">
                                                </td>
                                                <td>
                                                    <h2 class="textMenu">{{ dish.dishName }}</h2>
                                                    <h4 class="textPrix"> {{ dish.price }} € </h4>
                                                    <h6 class="textDesc"> {{ dish.description }} </h6>
                                                </td>
                                                <td>
                                                    {% if value != 1 %}
                                                        <a href="{{ path('minus') }}?idDish={{ dish.id }}&idCart={{ cart[0].id }}" class="sign">
                                                            -
                                                        </a>
                                                    {% endif %}
                                                </td>
                                                <td>
                                                    <h2 class="textDesc"> {{ value }} </h2>
                                                </td>
                                                <td>
                                                    <a href="{{ path('plus') }}?idDish={{ dish.id }}" class="sign">
                                                        +
                                                    </a>
                                                </td>
                                                <td>
                                                    <a href="{{ path('remove') }}?idDish={{ dish.id }}&idCart={{ cart[0].id }}" class="btn btn-primary btn-sm"> {{ "Remove" |trans}}  </a>
                                                </td>
                                            </tr>
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                    {% for c in cart|slice(-1) %}
                        {% if c.status == "open" and c.idDish is not empty  %}
                            <tr>
                                <td colspan="6">
                                    <h3 class="textPrix">Total : {{ total }} €</h3>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="6" style="text-align: center">
                                    <a href="{{ path('make-order')}}?total={{ total }}" class="btn btn-primary btn-lg btn-block"> {{ "Order" |trans}}  </a>
                                </td>
                            </tr>

                        {% else %}
                            <tr>
                                <td style="text-align: center">
                                    <p class="card-text"> {{ "Cart is empty ?" |trans}} <a href="{{ path('menu') }}">{{ "Choose your menu here !" |trans}}</a></p>
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contact{% endblock %}

{% block body %}

    <div class="shadow-lg p-3 mb-5 bg-white rounded">
        <div class="card text-center">
            <div class="card-header">
                {{ "Need help ?" |trans}}
            </div>
            <div class="card-body">
                <h5 class="card-title"> {{ "If you reach out, we will always take care of you !" |trans}} </h5>
                <p class="card-text">{{ "Describe your problem and our team is here to respond to any of your requests" |trans}} </p>
                <div class="ma-form">
                    {{ form_start(formMsg) }}
                        <div class="form-group">
                            {{form_label(formMsg.object, 'Object')}}
                            <div class="border-class">
                                {{form_widget(formMsg.object)}}
                            </div>
                        </div>
                        <div class="form-group">
                            {{form_label(formMsg.message, 'Tell us more...')}}
                            <div class="border-class">
                                {{ form_widget(formMsg.message) }}
                            </div>
                        </div>
                    <button type="submit" class="btn btn-primary btn-lg btn-block">{{ "Send" |trans}} </button>
                    {{ form_end(formMsg) }}
                </div>
            </div>
            <div class="card-footer text-muted">
                GustoHelpService
            </div>
        </div>

    </div>

{% endblock %}

templates/user/favorite.html.twig
{% extends 'base.html.twig' %}
{% block header %} <link rel="stylesheet" href="{{ asset('css/menuStyle.css') }}" />{% endblock %}
{% block title %}Favorites{% endblock %}

{% block body %}

    <div class="shadow-lg p-5 mb-5 bg-white rounded container">

        <div class="card text-center">
            <div class="card-header">
                {{ "Favorites" |trans}}
            </div>
            <div class="card-body">
                <h5 class="card-title"> {{ "Coming back for your best picks ?" |trans}} </h5>
                <p class="card-text">{{ "Gusto will never fail you ! MAMMA MIA " |trans}} !</p>
                <table class="table">
                    {% for fav in favs %}
                        {% if fav.idUser == app.user.id %}
                            {% for dish in dishes %}
                                {% if dish.id == fav.idDish %}
                                    {% if dish.archived != 1 %}
                                        <tbody>
                                        <tr>
                                            <td>
                                                <img class="imgMenu" src="{{ asset(dish.photo) }}" alt="{{ dish.dishName }}">
                                            </td>
                                            <td>
                                                <h2 class="textMenu">{{ dish.dishName }}</h2>
                                                <h4 class="textPrix"> {{ dish.price }} € </h4>
                                                <h6 class="textDesc"> {{ dish.description }} </h6>
                                            </td>
                                            <td>
                                                <a href="{{ path('del-fav') }}?idFav={{ fav.id }}" class="btn btn-outline-primary"> {{ "Remove" |trans}}  </a>
                                                <a href="{{ path('add-cart') }}?idDish={{ dish.id }} " class="btn btn-outline-primary"> {{ "Add to Cart" |trans}}  </a>
                                            </td>
                                        </tr>
                                        </tbody>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                </table>
                <div class="card-footer text-muted">
                    GustoHelpService
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/user/orderConfirmation.html.twig
{% extends 'base.html.twig' %}
{% block header %} <link rel="stylesheet" href="{{ asset('css/menuStyle.css') }}" />{% endblock %}

{% block title %}Cart{% endblock %}

{% block body %}
<div class="shadow-lg p-5 mb-5 bg-white rounded container">
    <div class="card text-center">
        <div class="card-header">
            {{ "Your order" |trans}}
        </div>
        <div class="card-body">
            <h5 class="card-title"> {{ "Here's a recap of your order." |trans}} </h5>
            <p class="card-text"> {{ "Please, verify all details before confirming your cart." |trans}}  </p>
            <table class="table">

                {% for c in cart %}
                    {% if c.status == "open" %}
                        {% for key, value in c.idDish %}
                            {% for dish in dishes %}
                                {% if dish.id == key %}
                                    {% if dish.archived != 1 %}
                                        <tr>
                                            <td>
                                                <img class="imgMenu" src="{{ asset(dish.photo) }}" alt="{{ dish.dishName }}">
                                            </td>
                                            <td>
                                                <h2 class="textMenu">{{ dish.dishName }}</h2>
                                                <h4 class="textPrix"> {{ dish.price }} € </h4>
                                                <h6 class="textDesc"> {{ dish.description }} </h6>
                                            </td>
                                            <td>
                                                <h2 class="textDesc"> x{{ value }} </h2>
                                            </td>
                                        </tr>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                        {% endfor %}
                        <tr>
                            <td colspan="3" style="text-align: center">
                                <h3 class="textPrix">Total : {{ total }} €</h3>
                                <h4> Deliver to : {{ app.user.adress }} </h4>
                            </td>
                        </tr>

                        <tr>
                            <td colspan="3" style="text-align: center">
                                <a href="{{ path('cart') }}" class="btn-lg btn-outline-primary"> {{ "Back to cart" |trans}} </a>
                                <a href="{{ path('order')}}?idCart={{ c.id }}&total={{ total }}" class="btn-lg btn-primary"> {{ "Confirm" |trans}} </a>
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}


            </table>
        </div>

    </div>
</div>

{% endblock %}

templates/user/updateInfoClient.html.twig
{% extends 'base.html.twig' %}

{% block title %}Update Info Client{% endblock %}

{% block body %}

    <div class="container-fluid content">
        <div class = "row">
            <div class="col-6 my-auto">
                {{ form_start(updateInfoForm) }}
                    <div class="ma-form">
                        <div class="form-group">
                            {{ form_label(updateInfoForm.id_user, 'Username') }}
                            <div class="border-class">
                                {{form_widget(updateInfoForm.id_user, {'attr': {'class': 'border-class'}})}}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                {{ form_label(updateInfoForm.id_user, 'Last Name') }}
                                <div class="border-class">
                                    {{ form_widget(updateInfoForm.lastName, {'attr': {'class': 'border-class'}}) }}
                                </div>
                            </div>
                            <div class="form-group col-md-6">
                                {{ form_label(updateInfoForm.id_user, 'First Name') }}
                                <div class="border-class">
                                    {{ form_widget(updateInfoForm.firstName, {'attr': {'class': 'border-class'}}) }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                {{ form_label(updateInfoForm.id_user, 'Email') }}
                                <div class="border-class">
                                    {{ form_widget(updateInfoForm.mail, {'attr': {'class': 'border-class'}}) }}
                                </div>
                            </div>
                            <div class="form-group col-md-6">
                                {{ form_label(updateInfoForm.id_user, 'Full adress') }}
                                <div class="border-class">
                                    {{ form_widget(updateInfoForm.adress, {'attr': {'class': 'border-class'}}) }}
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            {{ form_label(updateInfoForm.id_user, 'Gender') }}
                            <div class="border-class">
                                {{ form_widget(updateInfoForm.gender, {'attr': {'class': 'border-class'}}) }}
                            </div>
                        </div>

                        <div class="form-group">
                            {{ form_label(updateInfoForm.id_user, 'Password') }}
                            <div class="border-class">
                                {{ form_widget(updateInfoForm.plainPassword, {'attr': {'class': 'border-class'}}) }}
                            </div>

                        </div>
                        <button type="submit" class="btn btn-primary btn-lg btn-block">{{ "UPDATE" |trans}} </button>
                        <div class="form-check-label text-center">
                            {{ form_row(updateInfoForm.agreeTerms)  }}
                        </div>
                    </div>
                {{ form_end(updateInfoForm) }}
            </div>

            <div class="col-4">
                <div class="titre-border mb-4 ml-0">
                    <p class="text-center h2 my-2">{{ "Update your profile" |trans}} </p>
                </div>
                <div class="col-5">
                    <img src="{{ asset('image/CHEZ_GUSTO_LOGO.png') }}" alt="logo chez-gusto"/>
                </div>
            </div>

        </div>
    </div>

{% endblock %}